CREATE TABLE `taller_virtual` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NIVEL` varchar(255) DEFAULT NULL,
  `TITULO` varchar(255) DEFAULT NULL,
  `DESCRIPCION` varchar(255) DEFAULT NULL,
  `TECNOLOGIAS` varchar(255) DEFAULT NULL,
  `NOMBRE_TUTOR` varchar(255) DEFAULT NULL,
  `FECHA` datetime DEFAULT NULL,
  `RUTA_EMEBIDA` varchar(255) DEFAULT NULL,
  `RUTA_YOUTUBE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
)

